### ISSUE TITLE
Error about CLIP installation

### ISSUE THREAD

**Issue by hangzhiyiwei** [Jeeseung-Park/VIPLO#4]
Hi @Jeeseung-Park ,

Thanks for your nice work!
After I installed the repository step by step and run the inference command
"python test.py --detection-dir hicodet/detections/test2015_upt_vitpose --model-path checkpoints/best_hicodet.pt "

The error occurs:
"Traceback (most recent call last):
  File "test.py", line 19, in <module>  
    from models import VIPLO
  File "/home/hzyw/ViPLO/models.py", line 24, in <module>
    import clip
  File "/home/hzyw/anaconda3/envs/pocket/lib/python3.8/site-packages/clip/__init__.py", line 1, in <module>
    from .clip import *
  File "/home/hzyw/anaconda3/envs/pocket/lib/python3.8/site-packages/clip/clip.py", line 13, in <module>
    from .model import build_model
  File "/home/hzyw/anaconda3/envs/pocket/lib/python3.8/site-packages/clip/model.py", line 170, in <module>
    linear = _add_docstr(
RuntimeError: function 'linear' already has a docstring
"

I think it is a problem with the clip. Even, when I only write "import clip", the same error will occur. I don't know what's wrong here. Any reply will be appreciated. Thanks very much.

Best,
hangzhiyiwei

**Comment by Jeeseung-Park** [comment]
Sorry for the bug. You can just comment out or delete the `linear = _add_docstr(` part. We fix the bug and update the repo, so if you clone the repo again, the error will be solved.
Thank you.

**Comment by hangzhiyiwei** [comment]
Thanks for your reply.
